In [34]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [15]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
# converting categorical variables to numerical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = le.fit_transform(df[column])

In [18]:
# separating input and output variables
x = df.drop('Churn', axis=1)
y = df['Churn']

print(x,"\n",y)

      customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0           5375       0              0        1           0       1
1           3962       1              0        0           0      34
2           2564       1              0        0           0       2
3           5535       1              0        0           0      45
4           6511       0              0        0           0       2
...          ...     ...            ...      ...         ...     ...
7038        4853       1              0        1           1      24
7039        1525       0              0        1           1      72
7040        3367       0              0        1           1      11
7041        5934       1              1        1           0       4
7042        2226       1              0        0           0      66

      PhoneService  MultipleLines  InternetService  OnlineSecurity  \
0                0              1                0               0
1                1              0                0               2
2                1              0                0               2
3                0              1                0               2
4                1              0                1               0
...            ...            ...              ...             ...
7038             1              2                0               2
7039             1              2                1               0
7040             0              1                0               2
7041             1              2                1               0
7042             1              0                1               2

      OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0                2                 0            0            0
1                0                 2            0            0
2                2                 0            0            0
3                0                 2            2            0
4                0                 0            0            0
...            ...               ...          ...          ...
7038             0                 2            2            2
7039             2                 2            0            2
7040             0                 0            0            0
7041             0                 0            0            0
7042             0                 2            2            2

      StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
0                   0         0                 1              2
1                   0         1                 0              3
2                   0         0                 1              3
3                   0         1                 0              0
4                   0         0                 1              2
...               ...       ...               ...            ...
7038                2         1                 1              3
7039                2         1                 1              1
7040                0         0                 1              2
7041                0         0                 1              3
7042                2         2                 1              0

      MonthlyCharges  TotalCharges
0              29.85          2505
1              56.95          1466
2              53.85           157
3              42.30          1400
4              70.70           925
...              ...           ...
7038           84.80          1597
7039          103.20          5698
7040           29.60          2994
7041           74.40          2660
7042          105.65          5407

[7043 rows x 20 columns]
 0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [19]:
#splitting training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(len(x_train))
print(len(x_test))

5634
1409

In [20]:
# training the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
print("Model trained successfully")

Model trained successfully

c:\Users\ankat\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
# calculating m & c value
m= model.coef_[0][0]
c= model.intercept_[0]
print("m value:",m)
print("c value:",c)

m value: -5.2238168458135527e-05
c value: -0.17964518081409003

In [30]:
x=5
z=m*x + c
print("for x =",x,"calculated z value is ",z)
probability = 1/(1+np.exp(-z))
print("Probability:",probability)

if probability>0.6:
    print("Churn : Yes")
else:
    print("Churn: No")

y_pred = model.predict(x_test)
print("Predicted values:\n",y_pred)
comparison = pd.DataFrame({"Actual":y_test.values.flatten(),"Predicted":y_pred})
print(comparison)

for x = 5 calculated z value is  -0.1799063716563807
Probability: 0.45514432623162143
Churn: No
Predicted values:
 [1 0 0 ... 0 0 0]
      Actual  Predicted
0          1          1
1          0          0
2          0          0
3          1          1
4          0          0
...      ...        ...
1404       0          0
1405       0          0
1406       0          0
1407       0          0
1408       1          0

[1409 rows x 2 columns]

In [31]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[923 113]
 [165 208]]

In [32]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)
precision = precision_score(y_test,y_pred)
print("Precision:",precision)
recall = recall_score(y_test,y_pred)
print("Recall:",recall)
f1 = f1_score(y_test,y_pred)
print("F1 Score:",f1)

Accuracy: 0.8026969481902059
Precision: 0.6479750778816199
Recall: 0.5576407506702413
F1 Score: 0.5994236311239193

In [33]:
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)
print("Classification Report:\n",report)

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.89      0.87      1036
           1       0.65      0.56      0.60       373

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.73      1409
weighted avg       0.80      0.80      0.80      1409